remote_theme: jekyll-minima
plugins:
  - jekyll-remote-theme

skin: dark

title: Ishan Manjrekar
subtitle: game designer

# Optional settings
description: A brief description of your site
author: Your Name

# Build settings
markdown: kramdown
